// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbxzu0Ago9HS9DFD3eEhm5_09RLag1Onk',
    appId: '1:564733805208:web:dc16f671e56f9b16eac6ed',
    messagingSenderId: '564733805208',
    projectId: 'crypto-wallet-6b734',
    authDomain: 'crypto-wallet-6b734.firebaseapp.com',
    storageBucket: 'crypto-wallet-6b734.appspot.com',
    measurementId: 'G-H4WKVGYV3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiVq6FZ5a0UbIyL5hDZiYwxJJRd3U2gjw',
    appId: '1:564733805208:android:10162189af870194eac6ed',
    messagingSenderId: '564733805208',
    projectId: 'crypto-wallet-6b734',
    storageBucket: 'crypto-wallet-6b734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvFzgU08s0rMUBPPs76GVLpSaXi032g_A',
    appId: '1:564733805208:ios:dd607abbef32a94ceac6ed',
    messagingSenderId: '564733805208',
    projectId: 'crypto-wallet-6b734',
    storageBucket: 'crypto-wallet-6b734.appspot.com',
    iosClientId:
        '564733805208-5r196pr494h8vj1o5bhsqreqr5ikfahd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );
}
